#!/usr/bin/env bash
podman volume create mongo --ignore
podman run \
    -d \
    --replace \
    --rm \
    --name mongo \
    -p 127.0.0.1:27000:27000 \
    -v mongo:/data/db \
    docker.io/mongo:latest
