#!/usr/bin/env bash
podman volume create postgres --ignore
podman run \
    -d \
    --replace \
    --rm \
    --name postgres \
    -p 5432:5432 \
    -v postgres:/var/lib/postgresql/data \
    -e "POSTGRES_PASSWORD=postgres" \
    docker.io/postgres:latest
